export enum ScrollDirection {
  SCROLL_NONE,
  SCROLL_BACKWARD,
  SCROLL_FORWARD,
}

export enum Position {
  TOP,
  RIGHT,
  BOTTOM,
  LEFT,
}

export const OPTIONS_DEFAULT_SUBDOMAIN_WIDTH = 10;
export const OPTIONS_DEFAULT_SUBDOMAIN_HEIGHT = 10;
export const OPTIONS_DEFAULT_SUBDOMAIN_GUTTER = 2;
export const OPTIONS_DEFAULT_SUBDOMAIN_RADIUS = 0;
export const SCALE_BASE_OPACITY_COLOR = 'red';
